# Generated by Django 4.1 on 2022-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(related_name='vendors', to='vendor.vendor'),
        ),
    ]
