# Generated by Django 4.1 on 2022-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('order', '0002_alter_order_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(related_name='vendor', to='vendor.vendor'),
        ),
    ]
